# Generated by Django 5.1.2 on 2024-10-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_linting"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Linting",
            new_name="Listing",
        ),
    ]
